### ISSUE TITLE
Broken on 1.16

### ISSUE THREAD

**Issue by soshimee** [MieskeB/mc-fakeblock#1]
`/fb create <coords> <block>` says incorrect usage.
Used something like: `/fb create 100 28 100 stone`

**Comment by MieskeB** [comment]
The block isn't required. The block in that location is the block that is used.

So enter the command without the block:
`/fb create 28 64 19`

**Comment by soshimee** [comment]
Just thought that I needed the block, I will see if that works.

**Comment by MieskeB** [comment]
@soshimee did it work?
